export async function generatePDF(report: any) {
  const analysis = report.analysis;
  if (!analysis) return;

  const vulnLabels: Record<string, string> = {
    dataPrivacy: "Data Privacy",
    promptInjection: "Prompt Injection",
    modelBias: "Model Bias",
    infrastructureSecurity: "Infrastructure Security",
    outputReliability: "Output Reliability",
    complianceRisk: "Compliance Risk",
  };

  const vulnRows = Object.entries(analysis.vulnerabilities || {})
    .map(([key, val]: [string, any]) => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #1a1a2e;">${vulnLabels[key] || key}</td>
        <td style="padding:8px;border-bottom:1px solid #1a1a2e;text-align:center;color:${val.score >= 7 ? '#ef4444' : val.score >= 4 ? '#eab308' : '#22c55e'};font-weight:bold;">${val.score}/10</td>
        <td style="padding:8px;border-bottom:1px solid #1a1a2e;color:#888;font-size:12px;">${val.details}</td>
      </tr>
    `).join('');

  const compRows = (analysis.competitors || [])
    .map((c: any) => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #1a1a2e;font-weight:500;">${c.name}</td>
        <td style="padding:8px;border-bottom:1px solid #1a1a2e;text-align:center;">${c.trustScore}</td>
        <td style="padding:8px;border-bottom:1px solid #1a1a2e;font-size:12px;">${c.pricing}</td>
        <td style="padding:8px;border-bottom:1px solid #1a1a2e;font-size:12px;">${c.securityFeatures}</td>
      </tr>
    `).join('');

  const feedItems = (analysis.knowledgeFeed || []).slice(0, 8)
    .map((item: any) => `
      <div style="margin-bottom:12px;padding:10px;background:#111;border-radius:6px;">
        <div style="font-weight:500;margin-bottom:4px;">${item.title}</div>
        <div style="font-size:11px;color:#888;margin-bottom:4px;">${item.source} · ${item.date} · <span style="color:${item.credibility === 'High' ? '#22c55e' : item.credibility === 'Medium' ? '#eab308' : '#ef4444'}">${item.credibility} credibility</span></div>
        <div style="font-size:12px;color:#aaa;">${item.snippet}</div>
      </div>
    `).join('');

  const scoreColor = analysis.trustScore >= 70 ? '#22c55e' : analysis.trustScore >= 40 ? '#eab308' : '#ef4444';

  const html = `
    <html>
    <head>
      <style>
        @page { margin: 40px; size: A4; }
        body { font-family: 'Helvetica Neue', Arial, sans-serif; background: #0a0a0a; color: #e8eaed; margin: 0; padding: 40px; }
        h1, h2 { margin: 0 0 16px 0; }
        table { width: 100%; border-collapse: collapse; }
        th { text-align: left; padding: 8px; border-bottom: 2px solid #3b82f6; color: #3b82f6; font-size: 13px; }
      </style>
    </head>
    <body>
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:32px;padding-bottom:16px;border-bottom:1px solid #222;">
        <div style="width:36px;height:36px;border-radius:8px;background:#3b82f6;display:flex;align-items:center;justify-content:center;font-weight:bold;color:white;">A</div>
        <div>
          <h1 style="font-size:22px;margin:0;">AI Security Insight — Intelligence Report</h1>
          <div style="font-size:12px;color:#888;">Generated ${new Date(report.created_at).toLocaleString()} · clarier.ai</div>
        </div>
      </div>

      <div style="display:flex;align-items:center;gap:24px;margin-bottom:32px;">
        <div style="text-align:center;">
          <div style="font-size:48px;font-weight:bold;color:${scoreColor};">${analysis.trustScore}</div>
          <div style="font-size:12px;color:#888;">Trust Score</div>
        </div>
        <div style="flex:1;">
          <h2 style="font-size:16px;">Executive Summary — ${report.service_name}</h2>
          <p style="color:#aaa;font-size:13px;line-height:1.6;">${analysis.executiveSummary}</p>
        </div>
      </div>

      <h2 style="font-size:16px;color:#3b82f6;">Vulnerability Assessment</h2>
      <table style="margin-bottom:32px;">
        <thead><tr><th>Category</th><th>Risk</th><th>Details</th></tr></thead>
        <tbody>${vulnRows}</tbody>
      </table>

      <h2 style="font-size:16px;color:#3b82f6;">Competitive Comparison</h2>
      <table style="margin-bottom:32px;">
        <thead><tr><th>Service</th><th>Trust</th><th>Pricing</th><th>Security</th></tr></thead>
        <tbody>${compRows}</tbody>
      </table>

      <h2 style="font-size:16px;color:#3b82f6;">Intelligence Feed</h2>
      ${feedItems}

      <div style="margin-top:40px;padding-top:16px;border-top:1px solid #222;font-size:11px;color:#555;">
        This report was generated by AI Security Insight (clarier.ai). Information is gathered from public sources and AI analysis. This is not legal or compliance advice. Trust scores are indicative and should be verified independently.
      </div>
    </body>
    </html>
  `;

  // Open in new window for printing as PDF
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }
}
